"""x

Revision ID: 03489c582500
Revises: 0003_drop_server_defaults
Create Date: 2026-08-21 23:22:36.680084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03489c582500'
down_revision = '0003_drop_server_defaults'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_entity_type'))
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_area_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_constraint(batch_op.f('fk_tasks_deleted_by_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_area_id'), type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('area_id')
        batch_op.drop_column('visibility')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_area_lead')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_area_lead', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('area_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_area_id'), 'areas', ['area_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tasks_deleted_by_id'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_area_id'), ['area_id'], unique=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###
